#
# Copyright 2017-2026 The OpenTracing Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# Rule configuration.
# For rule descriptions and how to fix: https://github.com/DavidAnson/markdownlint/tree/main#rules--aliases
config:
  ul-style:
    style: dash
  no-duplicate-heading:
    siblings_only: true
  line-length:
    line_length: 500
    code_blocks: false
    tables: false
  first-line-h1: false

# Define glob expressions to ignore
ignores:
  - '.github/**'

# Fix any fixable errors
fix: true
